version: "3.3"
services:
  # Traefik to mimic the kubernetes ingress
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8002:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - victi-platform_default
      - chatbot-interface_default

networks:
  victi-platform_default:
    external:
      name: victi-platform_default
  chatbot-interface_default:
    external:
      name: chatbot-interface_default
