version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
    - "8002:80"

    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  app1:
    image: test/node-web-app 
    ports: 
    - "8003:8080"


  app2:
    image: test/node-web2 
    ports: 
    - "8004:8080"
