apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: dockerid978/devops:appv1  # Replace with your Docker image
          ports:
            - containerPort: 8080