apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the service
      targetPort: 8080  # The port your container is listening on
  type: NodePort  # Exposes the service to the outside world